name: contract-analysis
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - jupyter
  - notebook
  - ipykernel
  - pip
  - pip:
    - pandas>=2.0.0
    - numpy>=1.20.0
    - matplotlib>=3.5.0
    - seaborn>=0.11.0
    - scikit-learn>=1.0.0
    - joblib>=1.1.0
    - pandera>=0.20.0
    - great-expectations>=0.15.0
    - spacy>=3.5.0
    - transformers>=4.20.0
    - torch>=1.12.0
    - pytest>=7.0.0
    - pytest-cov>=4.0.0
    - black>=22.0.0
    - flake8>=5.0.0
    - mypy>=1.0.0
    - dvc>=3.0.0
