name: legal-ai
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - jupyter
  - ipykernel
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - seaborn
  - pip:
    - torch>=2.0.0
    - transformers>=4.30.0
    - sentence-transformers>=2.2.0
    - fastapi>=0.100.0
    - streamlit>=1.25.0
    - chromadb>=0.4.0
    - mlflow>=2.6.0
    - openai>=1.0.0
    - shap>=0.42.0
    - pytest>=7.4.0
    - black>=23.7.0
    - flake8>=6.0.0
    - pre-commit>=3.3.0
    - python-dotenv>=1.0.0
    - rich>=13.4.0
    - tqdm>=4.65.0
