# Model Configuration
# Phase 1: Baseline Models

# Data configuration
data:
  train_split: 0.8
  val_split: 0.1
  test_split: 0.1
  random_state: 42
  stratify: true

# Feature engineering
features:
  tfidf_max_features: 5000
  tfidf_ngram_range: [1, 3]
  tfidf_min_df: 2
  tfidf_max_df: 0.95
  use_idf: true

# Model configuration
models:
  logistic_regression:
    C: 1.0
    max_iter: 1000
    class_weight: "balanced"
    random_state: 42
  
  random_forest:
    n_estimators: 100
    max_depth: 10
    min_samples_split: 5
    min_samples_leaf: 2
    class_weight: "balanced"
    random_state: 42

# Training configuration
training:
  cv_folds: 5
  scoring: "f1_macro"
  n_jobs: -1
  verbose: 1

# Evaluation configuration
evaluation:
  metrics: ["accuracy", "precision_macro", "recall_macro", "f1_macro"]
  confusion_matrix: true
  classification_report: true
  feature_importance: true
  top_features: 10

# Risk scoring configuration
risk_scoring:
  high_risk_threshold: 7
  medium_risk_threshold: 4
  low_risk_threshold: 1
  risk_keywords:
    high:
      - "unlimited liability"
      - "indemnification"
      - "force majeure"
      - "termination for convenience"
    medium:
      - "payment terms"
      - "confidentiality"
      - "non-compete"
      - "intellectual property"
    low:
      - "definitions"
      - "notices"
      - "governing law"
      - "entire agreement"
